// ColorSelector.idl : IDL source for ColorSelector
//

// This file will be processed by the MIDL tool to
// produce the type library (ColorSelector.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(43FA8B14-CEA4-4531-8745-4204A2F26995),
	version(1.0),
	helpstring("ColorSelector 1.0 Type Library")
]
library ColorSelectorLib
{
	importlib("stdole2.tlb");
};
